### ISSUE TITLE
GLB Animations

### ISSUE THREAD

**Issue by crazyramirez** [readyplayerme/animation-library#2]
Hi guys!

Thanks for the great contribution, the animations are impeccable.
I usually work a lot of projects in BabylonJS and the file standard it uses is GLB.

I have used a mini App developed in NodeJS to batch convert from FBX to GLB and optimize the animations:

https://github.com/crazyramirez/FBX2GLB-Batch-Convert-Optimizer

I have also uploaded to Github an example combining multiple animations in a ReadyPlayerMe Character:

https://github.com/crazyramirez/babylonjs-ReadyPlayerMe-Animation-Combiner

Live Demo TEST

https://viseni.com/readyplayer_anim/

Live DEMO TEST using Morph Targets Animation

https://viseni.com/readyplayer_talk/

I hope you enjoy it.

Thanks again for your work.

**Comment by tiivik** [comment]
Thanks for the feedback, looking great!

We provided them as FBX first to work in Unity & Unreal, and looking into providing GLB-formatted variants as well, which is easier to work with across the web.

**Comment by brettkromkamp** [comment]
Having GLB-formatted variants would be excellent. Until then, hopefully tools as provided by @crazyramirez will have to fill the gap for the glTF-based ecosystems (three.js, BabylonJS, etcetera).

Anyway... thanks for the fantastic contribution.

**Comment by MAG-DanielMurdolo** [comment]
Adding my vote to a request for GLB files so we can use these excellent assets in even more places.

**Comment by brettkromkamp** [comment]
Mixamo's FBX animations can be used, as-is, with three.js/Reach Three Fiber/drei. But, these animations, when attempting to load them fail with the following error: `Could not load ./animations/backflip.fbx: THREE.FBXLoader: Cannot find the version number for the file given.`

**Comment by lenkawell** [comment]
Adding GLB versions would be nice, but along with Unreal and Unity, the Movie Maker 3D iOS and macOS apps version 11.0 now support importing FBX animations: https://moviemaker3d.com/avatar-character-body-animations

**Comment by MAG-DanielMurdolo** [comment]
I've created a fork with GLB versions. Do you have any guidelines to follow for creating a PR (if it's of interest)?

**Comment by fengxingshenzhou** [comment]
I encountered an error when converting Mixamo's FBX to GLB using Blender 4.0. The error message is as follows. Have you encountered it before?


runtimeAnimation.ts:336 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getLocalMatrix')
    at e._getOriginalValues (runtimeAnimation.ts:336:20)
    at new e (runtimeAnimation.ts:224:18)
    at e.appendAnimations (animatable.ts:198:41)
    at new e (animatable.ts:152:18)
    at Fr.beginDirectAnimation (animatable.ts:835:24)
    at a (animationGroup.ts:656:44)
    at e.start (babylon.js:1:675764)
    at animationBlending (main.js?id=79:510:12)
    at animationBlending.next (<anonymous>)
    at pn (coroutine.ts:46:32)

**Comment by tiivik** [comment]
GLB variants added by https://github.com/readyplayerme/animation-library/pull/12
